version: '3'
services:
  reacts:
    build: .
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    environment:
      - TOKEN=${TOKEN}
      - RUST_BACKTRACE=1
      - LOG_LEVEL=debug